import { User } from "@/types/user";

export const users: User[] = [
    {
        id: '1',
        fullName: 'Suman Shrestha',
        email: 'suman@example.com',
        phone: '+1-202-555-0101',
        role: 'User',
        gender: 'Male',
        address: 'Budhanilkantha, Nepal',
        appointmentTime: '2025-11-10T09:30:00',
        assignedDoctor: 'Dr. Priya Kapoor',
    },
    {
        id: '2',
        fullName: 'Savona Shrestha',
        email: 'savona@example.com',
        phone: '+1-202-555-0103',
        role: 'User',
        gender: 'Female',
        address: 'Budhanilkantha, Nepal',
        appointmentTime: '2025-11-11T14:00:00',
        assignedDoctor: 'Dr. Emily Stone',
    },
    {
        id: '3',
        fullName: 'Sandeep Shrestha',
        email: 'sandeep@example.com',
        phone: '+1-202-555-0102',
        role: 'User',
        gender: 'Male',
        address: '78 Maple Ave, Seattle, WA',
        appointmentTime: '2025-11-10T11:00:00',
        assignedDoctor: 'Dr. Daniel Park',
    },

    {
        id: '4',
        fullName: 'Ram Khan',
        email: 'ram@example.com',
        phone: '+1-202-555-0104',
        role: 'User',
        gender: 'Female',
        address: '221B Baker Rd, Boston, MA',
        appointmentTime: '2025-11-12T10:15:00',
        assignedDoctor: 'Dr. Priya Kapoor',
    },
    {
        id: '5',
        fullName: 'Prithivi Narayan Shah',
        email: 'prithivi@example.com',
        phone: '+1-202-555-0105',
        role: 'User',
        gender: 'Male',
        address: '450 Pine St, San Francisco, CA',
        appointmentTime: '2025-11-13T08:45:00',
        assignedDoctor: 'Dr. Daniel Park',
    },
    {
        id: '6',
        fullName: 'Paras Khadka',
        email: 'paras@example.com',
        phone: '+1-202-555-0106',
        role: 'User',
        gender: 'Female',
        address: '16 Willow Ct, Chicago, IL',
        appointmentTime: '2025-11-14T16:00:00',
        assignedDoctor: 'Dr. Emily Stone',
    },
    {
        id: '7',
        fullName: 'Asta Bakasta',
        email: 'asta@example.com',
        phone: '+1-202-555-0107',
        role: 'User',
        gender: 'Male',
        address: '305 River Rd, Portland, OR',
        appointmentTime: '2025-11-15T13:30:00',
        assignedDoctor: 'Dr. Michael Chen',
    },
    {
        id: '8',
        fullName: 'Zoe Martinez',
        email: 'zoe.martinez@example.com',
        phone: '+1-202-555-0108',
        role: 'User',
        gender: 'Female',
        address: '87 Sunset Blvd, Los Angeles, CA',
        appointmentTime: '2025-11-16T09:00:00',
        assignedDoctor: 'Dr. Michael Chen',
    },
    {
        id: '9',
        fullName: 'Noah Brown',
        email: 'noah.brown@example.com',
        phone: '+1-202-555-0109',
        role: 'User',
        gender: 'Male',
        address: '12 Cedar St, Denver, CO',
        appointmentTime: '2025-11-17T15:00:00',
        assignedDoctor: 'Dr. Aisha Rahman',
    },
    {
        id: '10',
        fullName: 'Sophia Rossi',
        email: 'sophia.rossi@example.com',
        phone: '+1-202-555-0110',
        role: 'User',
        gender: 'Female',
        address: '60 Harbor Dr, Miami, FL',
        appointmentTime: '2025-11-18T10:45:00',
        assignedDoctor: 'Dr. Aisha Rahman',
    },
    {
        id: '11',
        fullName: 'Dr. Priya Kapoor',
        email: 'priya.kapoor@hospital.org',
        phone: '+1-202-555-0111',
        role: 'Doctor',
        gender: 'Female',
        address: 'Cardiology Dept, Main Hospital, Floor 3',
        appointmentTime: null,
        assignedDoctor: null,
    },
    {
        id: '12',
        fullName: 'Dr. Daniel Park',
        email: 'daniel.park@hospital.org',
        phone: '+1-202-555-0112',
        role: 'Doctor',
        gender: 'Male',
        address: 'Orthopedics Dept, Main Hospital, Floor 2',
        appointmentTime: null,
        assignedDoctor: null,
    },
    {
        id: '13',
        fullName: 'Dr. Emily Stone',
        email: 'emily.stone@hospital.org',
        phone: '+1-202-555-0113',
        role: 'Doctor',
        gender: 'Female',
        address: 'Pediatrics Dept, Main Hospital, Floor 4',
        appointmentTime: null,
        assignedDoctor: null,
    },
    {
        id: '14',
        fullName: 'Dr. Michael Chen',
        email: 'michael.chen@hospital.org',
        phone: '+1-202-555-0114',
        role: 'Doctor',
        gender: 'Male',
        address: 'General Medicine, Clinic B, Floor 1',
        appointmentTime: null,
        assignedDoctor: null,
    },
    {
        id: '15',
        fullName: 'Dr. Aisha Rahman',
        email: 'aisha.rahman@hospital.org',
        phone: '+1-202-555-0115',
        role: 'Doctor',
        gender: 'Female',
        address: 'Neurology Dept, Main Hospital, Floor 5',
        appointmentTime: null,
        assignedDoctor: null,
    }
];